### ISSUE TITLE
Homepage- News Section: Not align when Post title "Latest News" was hidden. It should be aligned 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#101]
![image](https://cloud.githubusercontent.com/assets/18568310/14778063/778656ba-0b03-11e6-9971-c9847d60e334.png)

**Comment by ricatitan** [comment]
There should be no default value when there is no section title given.
![image](https://cloud.githubusercontent.com/assets/18568310/14876094/02eac870-0d44-11e6-8e75-6c10f5bc6660.png)

![image](https://cloud.githubusercontent.com/assets/18568310/14876096/0611b856-0d44-11e6-8609-40ff273ec853.png)

**Comment by ravititan** [comment]
As per the scope if there is no value in the field it should display "Latest Posts"
![aaa-101](https://cloud.githubusercontent.com/assets/13450891/14885096/1bfc38e4-0d67-11e6-94f2-5db55ecf29cc.jpg)

**Comment by roseliesromeo** [comment]
It is now aligned by adding a default value.  Previously, field can be empty.
