### ISSUE TITLE
Homepage - News Section: Not the same margin between the Post title and the image and it should have at least 27 px

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#103]
![image](https://cloud.githubusercontent.com/assets/18568310/14874120/bbaf8f36-0d2f-11e6-82cf-ed9876afa8d5.png)

**Comment by ravititan** [comment]
As the design has two lines with bottom margin of 27px , so if we have two line it will have 27px bottom margin or else it will be more than that.
