### ISSUE TITLE
FAQ: Text and arrow overlapped

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#116]
![image](https://cloud.githubusercontent.com/assets/18568310/14905691/c9e6e890-0de5-11e6-8fcc-63fc0f58927c.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/15004066/1acbcd22-11e5-11e6-9017-e431b2009a9f.png)
