### ISSUE TITLE
Admin(Gallery Page) : ACF field for Gallery images should be implemented

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/AAA-Production#13]
![8](https://cloud.githubusercontent.com/assets/13309806/14420883/17441f0c-ffec-11e5-8ead-b1e816c32b71.png)

**Comment by ravititan** [comment]
It has been implemented in the gallery option page. Please check the screenshot.
![gallery](https://cloud.githubusercontent.com/assets/13450891/14489955/9895bbae-018d-11e6-9165-ed6842b14a69.jpg)
