### ISSUE TITLE
Leadins : As per Scope Content and Read More button should be displayed

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/AAA-Production#29]
As per Scope Doc 'content text area' and 'Read More button lable' fields are there, But in design only title field is present.
 scope and design are conflicting.
Conform with PM for Fixing
![1](https://cloud.githubusercontent.com/assets/13309806/14521646/eb1d75f0-0247-11e6-8aa1-ea4034e3808d.png)
![2](https://cloud.githubusercontent.com/assets/13309806/14521647/ef1377b8-0247-11e6-904f-37a3be2d747c.png)

**Comment by ravititan** [comment]
It is a scope error there is no **'Content Area' or 'Read More Button'** mentioned in the design nor in the design brief.

![design-brief-screen](https://cloud.githubusercontent.com/assets/13450891/14554851/11b85732-030d-11e6-9d58-b1667e083c08.jpg)

**Comment by ravi-josyula** [comment]
Please remove unnecessary fields
![345](https://cloud.githubusercontent.com/assets/13309806/14555774/ee49837a-0311-11e6-8db9-a93588cf2e00.png)
