### ISSUE TITLE
Footer: Incorrect SEO Footer. It was mention in the scope to use SEO Footer 1

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#42]
Reference:
https://knowledgebase.titanweb.com.au/implementation/standard-pages/updating-the-footer-for-seo-ranking
![image](https://cloud.githubusercontent.com/assets/18568310/14667589/9d3379aa-0712-11e6-8649-b8bfacb46fcd.png)
![image](https://cloud.githubusercontent.com/assets/18568310/14667651/d7528d7e-0712-11e6-971a-e6faa37358e5.png)
![image](https://cloud.githubusercontent.com/assets/18568310/14667676/faad6ad2-0712-11e6-9e52-75ab19add7cb.png)

**Comment by ravititan** [comment]
As per the instructions from Jolene , We have to change the logo and the link as per the design.
