### ISSUE TITLE
Lead-ins: Read More Button is not in the design. Do we need to include this Read More button?

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#43]
If the button is not needed, kindly update the scope.

![image](https://cloud.githubusercontent.com/assets/18568310/14694477/61ee0f3e-079b-11e6-9e27-f463c5c32603.png)
![image](https://cloud.githubusercontent.com/assets/18568310/14694478/676d1298-079b-11e6-894b-c4debba2bf5f.png)

**Comment by ravititan** [comment]
Scope Updated.
