### ISSUE TITLE
Homepage Content: ACF- Facebook feed code and ACF- Background image are not implemented

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#44]
![image](https://cloud.githubusercontent.com/assets/18568310/14694608/8f9193b0-079c-11e6-8156-47b9fb4fef1d.png)

**Comment by ravititan** [comment]
For background image it is mentioned in scope to use featured image as background image.
![aaa-44](https://cloud.githubusercontent.com/assets/13450891/14818697/1e5365fe-0bdc-11e6-9428-4eb78fb4f6ff.jpg)
