### ISSUE TITLE
Homepage- News Section : Default image has incorrect image size

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#63]
It should have 240px w and 124px h
![image](https://cloud.githubusercontent.com/assets/18568310/14703030/3d5eb426-07e0-11e6-96db-b4253fa2c8cb.png)

**Comment by ravititan** [comment]
As per the design the size of image should be w270 X h124 
![aaa-63](https://cloud.githubusercontent.com/assets/13450891/14815782/f063b74a-0bca-11e6-8f26-dab886868eaa.jpg)
