### ISSUE TITLE
Homepage Content: Homepage title caters 2 lines. It should only cater 1 line.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/AAA-Production#90]
![image](https://cloud.githubusercontent.com/assets/18568310/14773501/67bc02aa-0add-11e6-9fe2-db90df3718a6.png)

**Comment by ravititan** [comment]
If we limit the title to 1 line it will not display the full title in devices, for instance we have **'Pro Audio Services And Event Management Perth' ** if we limit it to 1 line it will display **'Pro Audio Services And Event Management'** in Ipad.
